glados/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import manual_judge_server.urls
import web.urls

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^mjs/', include(manual_judge_server.urls, namespace='mjs')),
                       url(r'', include(web.urls, namespace='web')),
                       )

web/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = patterns('web.views',
                       url(r'^$', RedirectView.as_view(url=reverse_lazy('web:contest_list')), name='home'),  # TODO make it generic
                       url(r'^contest/$', 'contest_list', name='contest_list'),
                       url(r'^contest/create/$', 'contest_create', name='contest_create'),
                       url(r'^contest/(?P<contest_id>\d+)/$', 'contest_details', name='contest_details'),
                       url(r'^contest/(?P<contest_id>\d+)/results$', 'contest_results', name='contest_results'),
                       url(r'^contest/(?P<contest_id>\d+)/edit$', 'contest_edit', name='contest_edit'),
                       url(r'^contest/(?P<contest_id>\d+)/match/$', 'match_list', name='match_list'),
                       url(r'^contest/(?P<contest_id>\d+)/match/(?P<match_id>\d+)/$', 'match_details', name='match_details'),
                       url(r'^judge/$', 'judge_list', name='judge_list'),
                       url(r'^judge/create/$', 'judge_create', name='judge_create'),
                       url(r'^judge/(?P<judge_id>\d+)/$', 'judge_details', name='judge_details'),
                       url(r'^judge/(?P<judge_id>\d+)/edit$', 'judge_edit', name='judge_edit'),
                       url(r'^program/$', 'program_list', name='program_list'),
                       url(r'^program/(?P<program_id>\d+)/$', 'program_details', name='program_details'),
                       url(r'^user/$', 'user_list', name='user_list'),
                       url(r'^user/(?P<user_id>\d+)/$', 'user_details', name='user_details'),
                       url(r'^login/$', 'login_view', name='login'),
                       url(r'^logout/$', 'logout_view', name='logout'),
                       )

web/templates/web/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>{# TODO read title from database #}
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}web/css/base.css">
    {% endblock %}
    {% block scripts %}
        <script type="application/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script type="application/javascript" src="{% static 'web/js/base.js' %}"></script>
    {% endblock %}
</head>
<body>
{% block banner %}
    <div class="banner">
        <a href="{% url 'web:home' %}"><img class="banner" alt="" src="{% static 'web/img/banner.png' %}"></a>
    </div>
{% endblock %}
<div class="site_wrapper">
    {% block login %}
    {% endblock %}
    <div class="site_flex">
        <ul class="std main_menu">
            {% block main_menu %}
                {% include 'web/menu/site_menu.html' %}
            {% endblock %}
        </ul>
        <div class="content_wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

web/templates/web/contest_create.html
{% extends 'web/site.html' %}

{% block title %}
    {{ block.super }}
    - Contest Create
{% endblock %}

{% block content %}
    {% if error %}
        {{ error }}
    {% endif %}
    <form action="{{ request.get_full_path }}" method="post">{% csrf_token %}
        <ul>
            <li>
                <label>
                    Name:
                    <input type="text" name="contest_name">
                </label>
            </li>
            <li>
                <label>
                    Description:<br>
                    <textarea name="contest_description"></textarea>
                </label>
            </li>
            <li>
                <label>
                    Players:<br>
                    <input type="number" name="contest_players_count" value="1">
                </label>
            </li>
        </ul>
        <input type="hidden" name="create">
        <input type="submit" value="Create">
    </form>
{% endblock %}

web/templates/web/contest_details.html
{% extends 'web/site.html' %}

{% block title %}
    {{ block.super }}
    - Contests details
{% endblock %}

{% block content %}
    <table class="std horizontal">
        <tr>
            <th>Contest name:</th>
            <td>{% autoescape on %}{{ contest_info.name }}{% endautoescape %}</td>
        </tr>

        <tr>
            <th>Contest description:</th>
            <td>{% autoescape on %}{{ contest_info.description | linebreaksbr }}{% endautoescape %}</td>
        </tr>

        <tr>
            <th>Contest default_judge:</th>
            <td>{% autoescape on %}{{ contest_info.default_judge }}{% endautoescape %}</td>
        </tr>

        <tr>
            <th>Contest players_count:</th>
            <td>{% autoescape on %}{{ contest_info.players_count }}{% endautoescape %}</td>
        </tr>
    </table>

    <a href="{% url 'web:contest_results' contest_info.id %}">
        {{ contest_info.name }} contest results</a><br>

    <a href="{% url 'web:match_list' contest_info.id %}">matches</a><br>

    {% if user.is_staff %}
        <a href="{% url 'web:contest_edit' contest_info.id %}">edit</a>
    {% endif %}

{% endblock %}

web/templates/web/contest_edit.html
{% extends 'web/site.html' %}

{% block title %}
    {{ block.super }}
    - Contest Edit
{% endblock %}

{% block content %}
    {% if error %}
        {{ error }}
    {% endif %}
    <form action="{% url 'web:contest_edit' contest.id %}" method="post">
        {% csrf_token %}
        <table class="std horizontal">
            <tr>
                <th><label for="contest_edit_name">Contest name:</label></th>
                <td><input id="contest_edit_name" type="text" name="name" value="{{ contest.name }}"/></td>
            </tr>

            <tr>
                <th><label for="contest_edit_description">Contest description:</label></th>
                <td><textarea id="contest_edit_description" class="std" name="description">{{ contest.description }}</textarea></td>
            </tr>

            <tr>
                <th><label for="contest_edit_default_judge">Contest default_judge:</label></th>
                <td><select id="contest_edit_default_judge" name="default_judge">
                    <option value="None" {% if not contest.default_judge %}selected{% endif %}>--------</option>
                    {% for judge in judges %}
                        <option value="{{ judge.id }}" {% if contest.default_judge == judge %}selected{% endif %}>{{ judge }}</option>
                    {% endfor %}
                </select></td>
            </tr>

            <tr>
                <th><label for="contest_edit_players_count">Contest players_count:</label></th>
                <td><input id="contest_edit_players_count" type="number" name="players_count" value="{{ contest.players_count }}"></td>
            </tr>
        </table>
        <input type="submit" name="save" value="save">
    </form>
{% endblock %}

web/templates/web/contest_list.html
{% extends 'web/site.html' %}

{% block title %}
    {{ block.super }}
    - Contest List
{% endblock %}

{% block content %}
    Contests:
    <table class="std">
        <tr class="head">
            <th class="min_width">id</th>
            <th>Name</th>
            <th>Description</th>
        </tr>
        {% for contest in contests %}
            <tr class="{% cycle 'row1' 'row2' %} href" data-href="{% url 'web:contest_details' contest.id %}">
                <td>{{ contest.id }}</td>
                <td><a href="{% url 'web:contest_details' contest.id %}">{{ contest.name }}</a></td>
                <td>{{ contest.description }}</td>
            </tr>
        {% endfor %}
    </table>

    {% if user.is_staff %}
        <a href="{% url 'web:contest_create' %}?r={{ request.get_full_path | urlencode:'' }}">Create</a>
    {% endif %}
{% endblock %}

web/templates/web/contest_results.html
{% extends 'web/site.html' %}

{% block title %}
    {{ block.super }}
    - {{contest.name}} contest results
{% endblock %}

{% block content %}
    <p> {{contest.name}} contest </p> <br>
    Results:
    <table class="std">
        <tr class="head">
            <th>id</th>
            <th>Name</th>
            <th>wins</th>
            <th>defeats</th>
            <th>ties</th>
        </tr>
        {% for prog in programs %}
            <tr class="{% cycle 'row1' 'row2' %}">
                <td>{{ prog.id }}</td>
                <td>{{ prog.name }}</td>
                <td>{{ prog.wins }}</td>
                <td>{{ prog.defeats }}</td>
                <td>{{ prog.ties }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

web/templates/web/judge_details.html
{% extends 'web/site.html' %}

{% block title %}
    {{ block.super }}
    - Judge details
{% endblock %}

{% block content %}
    <table class="std horizontal">
        <tr>
            <th>Judge name:</th>
            <td>{% autoescape on %}{{ judge_info.name }}{% endautoescape %}</td>
        </tr>

        <tr>
            <th>Judge description:</th>
            <td>{% autoescape on %}{{ judge_info.description | linebreaksbr }}{% endautoescape %}</td>
        </tr>

        <tr>
            <th>Path:</th>
            <td>{% autoescape on %}{{ judge_info.path }}{% endautoescape %}</td>
        </tr>

        <tr>
            <th>Initial parameters:</th>
            <td>{% autoescape on %}{{ judge_info.init_parameters | linebreaksbr }}{% endautoescape %}</td>
        </tr>
    </table>

    {% if user.is_staff %}
        <a href="{% url 'web:judge_edit' judge_info.id %}">edit</a>
    {% endif %}

{% endblock %}

web/templates/web/judge_edit.html
{% extends 'web/site.html' %}

{% block title %}
    {{ block.super }}
    - Judge Edit
{% endblock %}

{% block content %}
    {% if error %}
        {{ error }}
    {% endif %}
    <form action="{% url 'web:judge_edit' judge.id %}" method="post">
        {% csrf_token %}
        <table class="std horizontal">
            <tr>
                <th><label for="edit_judge_name">Judge name:</label></th>
                <td><input id="edit_judge_name" type="text" name="name" value="{{ judge.name }}"/></td>
            </tr>
            
            <tr>
                <th><label for="edit_judge_path">Path:</label></th>
                <td><input id="edit_judge_path" type="text" name="path" value="{{ judge.path }}"/></td>
            </tr>

            <tr>
                <th><label for="edit_judge_description">Judge description:</label></th>
                <td><textarea id="edit_judge_description" class="std" name="description">{{ judge.description }}</textarea></td>
            </tr>

            <tr>
                <th><label for="edit_judge_init_parameters">Initial parameters:</label></th>
                <td><textarea id="edit_judge_init_parameters" class="std" name="init_parameters">{{ judge.init_parameters }}</textarea></td>
            </tr>

        </table>
        <input type="submit" name="save" value="save">
    </form>
{% endblock %}

web/templates/web/match_details.html
{% extends 'web/site.html' %}

{% block title %}
    {{ block.super }}
    - Match Details
{% endblock %}

{% block content %}
    {% if error %}
        <div style="text-align: center; font-weight: bold;">{{ error }}</div>
    {% endif %}
    <table class="std">
        <tr class="head">
            <th>User</th>
            <th>Program</th>
            <th>Score</th>
            <th>Comment</th>
        </tr>
        {% for result in match.programmatch_set.all %}
            <tr class="{% cycle 'row1' 'row2' %} href" data-href="{% url 'web:program_details' result.program.id %}">
                <td>{{ result.program.user }}</td>
                <td>{{ result.program }}</td>
                <td>{{ result.score }}</td>
                <td>{{ result.comment }}</td>
            </tr>
        {% endfor %}
    </table>
    {% if not match.ended  %}
        <div style="font-weight: bold; text-align: center; color: red;
            font-size: x-large;">Match in progress</div>
    {% endif %}
    {% if logs and user.is_staff or match.ended %}
    Logs:
    <table class="std">
        <tr class="head">
            <th class="min_width">Priority</th>
            <th>Body</th>
            <th>Date</th>
        </tr>
        {% for log in logs %}
            <tr class="{% cycle 'row1' 'row2' %}">
                <td>{{ log.priority }}</td>
                <td>{{ log.body | linebreaksbr }}</td>
                <td>{{ log.time.ctime }}</td>
            </tr>
        {% endfor %}
    </table>
    {% endif %}
{% endblock %}

web/templates/web/match_list.html
{% extends 'web/site.html' %}

{% block title %}
    {{ block.super }}
    - Match List
{% endblock %}

{% block content %}
    <table class="std">
        <tr class="head">
            <th class="min_width">id</th>
            <th>Date</th>
            <th>Ended</th>
        </tr>
        {% for match in matches %}
            <tr class="{% cycle 'row1' 'row2' %} href" data-href="{% url 'web:match_details' contest.id match.id %}">
                <td>{{ match.id }}</td>
                <td>{{ match.start.ctime }}</td>
                <td>{{ match.ended }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

web/templates/web/program_list.html
{% extends 'web/site.html' %}

{% block title %}
    {{ block.super }}
    - Program List
{% endblock %}

{% block content %}
    Programs:
    <table class="std">
        <tr class="head">
            <th class="min_width">id</th>
            <th>Name</th>
            <th>Wins</th>
            <th>Ties</th>
            <th>Defeats</th>
        </tr>
        {% for program in programs %}
            <tr class="{% cycle 'row1' 'row2' %} href" data-href="{% url 'web:program_details' program.id %}">
                <td>{% autoescape on %}{{ program.id }}{% endautoescape %}</td>
                <td>{% autoescape on %}{{ program.name }}{% endautoescape %}</td>
                <td>{% autoescape on %}{{ program.wins }}{% endautoescape %}</td>
                <td>{% autoescape on %}{{ program.ties }}{% endautoescape %}</td>
                <td>{% autoescape on %}{{ program.defeats }}{% endautoescape %}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

web/templates/web/site.html
{% extends 'web/base.html' %}

{% block title %}
    GLaDOS{# TODO read title from database #}
{% endblock %}

{% block login %}
    <div>
        {% include 'web/login_form.html' %}
    </div>
{% endblock %}

web/templates/web/user_list.html
{% extends 'web/site.html' %}

{% block title %}
    {{ block.super }}
    - User List
{% endblock %}

{% block content %}
    Users:
    <table class="std">
        <tr class="head">
            <th class="min_width">id</th>
            <th>Username</th>
        </tr>
        {% for user in users %}
            <tr class="{% cycle 'row1' 'row2' %} href" data-href="{% url 'web:user_details' user.id %}">
                <td>{{ user.id }}</td>
                <td><a href="{% url 'web:user_details' user.id %}">{{ user.username }}</a></td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

web/templates/web/validation_error.html
{% extends 'web/site.html' %}

{% block title %}
    {{ block.super }}
    - Validation erroValidation error
{% endblock %}

{% block content %}
    <ul class="std">
        <li>
            {% autoescape on %}{{ error }}{% endautoescape %}
        </li>
    </ul>

{% endblock %}