glados/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import manual_judge_server.urls
import web.urls

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^mjs/', include(manual_judge_server.urls, namespace='mjs')),
                       url(r'', include(web.urls, namespace='web')),
                       )

web/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = patterns('web.views',
                       url(r'^$', RedirectView.as_view(url=reverse_lazy('web:contest_list')), name='home'),  # TODO make it generic
                       url(r'^contest/$', 'contest_list', name='contest_list'),
                       url(r'^contest/create/$', 'contest_create', name='contest_create'),
                       url(r'^contest/(?P<contest_id>\d+)/$', 'contest_details', name='contest_details'),
                       url(r'^contest/(?P<contest_id>\d+)/results$', 'contest_results', name='contest_results'),
                       url(r'^contest/(?P<contest_id>\d+)/edit$', 'contest_edit', name='contest_edit'),
                       url(r'^contest/(?P<contest_id>\d+)/match/$', 'match_list', name='match_list'),
                       url(r'^contest/(?P<contest_id>\d+)/match/(?P<match_id>\d+)/$', 'match_details', name='match_details'),
                       url(r'^judge/$', 'judge_list', name='judge_list'),
                       url(r'^judge/create/$', 'judge_create', name='judge_create'),
                       url(r'^judge/(?P<judge_id>\d+)/$', 'judge_details', name='judge_details'),
                       url(r'^judge/(?P<judge_id>\d+)/edit$', 'judge_edit', name='judge_edit'),
                       url(r'^program/$', 'program_list', name='program_list'),
                       url(r'^program/(?P<program_id>\d+)/$', 'program_details', name='program_details'),
                       url(r'^user/$', 'user_list', name='user_list'),
                       url(r'^user/(?P<user_id>\d+)/$', 'user_details', name='user_details'),
                       url(r'^login/$', 'login_view', name='login'),
                       url(r'^logout/$', 'logout_view', name='logout'),
                       )

web/templates/web/menu/site_menu.html
{#TODO make templatetag#}
{% if user.is_authenticated %}
    <li class="href" data-href="{% url 'web:contest_list' %}"><a href="{% url 'web:contest_list' %}">Contests</a></li>
    <li class="href" data-href="{% url 'web:program_list' %}"><a href="{% url 'web:program_list' %}">Programs</a></li>
{% endif %}
{% if user.is_authenticated %}
    <li class="href" data-href="{% url 'web:user_list' %}"><a href="{% url 'web:user_list' %}">Users</a></li>
{% endif %}
{% if user.is_staff %}
    <li class="href" data-href="{% url 'web:judge_list' %}"><a href="{% url 'web:judge_list' %}">Judges</a></li>
{% endif %}